version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /Users/edawg/class/class_docker_kubernetes/frontend:/home/node/app
      - /home/node/app/node_modules
  tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /Users/edawg/class/class_docker_kubernetes/frontend:/home/node/app
        - /home/node/app/node_modules
      command: ["npm","run","test"]
